import type { Metadata } from 'next';
import { Space_Mono } from 'next/font/google';
import './globals.css';
import Logo from '@/components/TipCalculator/Logo';

const spaceMono = Space_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['700'],
  style: 'normal',
  variable: '--font-space-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col items-center w-screen pt-[50px] bg-light-grayish-cyan ${spaceMono.variable} lg:pt-[163px]`}
      >
        <div className="flex justify-center mb-[40.86px] lg:mb-[87.86]">
          <Logo />
        </div>
        {children}
      </body>
    </html>
  );
}
